### ISSUE TITLE
Request: the same but reachable by right clicking on a link in a page

### ISSUE THREAD

**Issue by klint** [paulgreg/rsstodolist-addon#1]
I was quite happy to discover this very handy addon yesterday, thanks! :)
Would it be possible to add a feature to it? Having a right-click option to be able to add a link in a page to an RSS feed (not only the URL of the page itself).
Thanks

**Comment by paulgreg** [comment]
Yes, that’s a good idea.
If I understand well, the use case is, on a web page, to right click on a link and send it to rsstodolist directly, without the need to open it. Is that correct ?

**Comment by klint** [comment]
Yes, that's exactly what I meant. Thanks

**Comment by paulgreg** [comment]
I’ve added a contextual menu in that branch : https://github.com/paulgreg/rsstodolist-addon/tree/rightclick
Can you try it please and tell me what you think ?
You’ll need to clone the project, switch the that branch then load it in your browser.

**Comment by klint** [comment]
Hi Grégory
Thanks a lot for developping this enhancement request.
Yet, as I don't know how to make a Firefox extension off a repository, I
need some time to test it (I have found some documentation about writing
webextensions).
I think I have to test it on the Developer Edition, because of the lack of
signature.


2017-06-29 8:06 GMT+02:00 Grégory Paul <notifications@github.com>:

**Comment by paulgreg** [comment]
I do not know if you need Firefox developer edition.
Here’s the way to load the extension under Firefox :
1/ clone the repo or download the zip (just make sure to be on the `rightclick` branch),
2/ go to menu > addons,
3/ then use the "gear" menu on the right side and select "debug addons",
4/ then "load temporary addon" and select directory where are the sources files.

**Comment by klint** [comment]
Ok, it worked :). I wasn't aware of the "debug addon" thing.
And so far, so good. It takes the last feed name set up when using the
toolbar button, right?
Thanks a lot


2017-07-01 20:03 GMT+02:00 Grégory Paul <notifications@github.com>:

**Comment by paulgreg** [comment]
Exactly. If the feed or the server has changed, the right click menu is updated.
I’l wait a little bit before publishing it on the Firefox / Chrome stores.
Tell me if you found any bug.

**Comment by paulgreg** [comment]
I’ve published the update to Chrome and Mozilla Addon store so I’m closing the issue. Thx for the idea.
